server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql:3307/db_1?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: user
    password: user1234
  mail:
    host: smtp.gmail.com
    username: testowy2.kmprograms@gmail.com
    password: jjtdkjurrfqdgqxu
    port: 587
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.from.email: testcars630@gmail.com

km-config:
   email:
    activation-mail-expiration-time: 300000000000
    #activation-mail-expiration-time: 5000000000
   tokens:
     access:
       expiration_time_ms: 300000
     refresh:
       expiration_time_ms: 30000000
       access_token_expiration_time_ms_property: 'access_token_expiration_time_ms_property'
     prefix: 'Bearer '