server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql:3307/db_1?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: user
    password: user1234
  mail:
    host: smtp.gmail.com
    username: testcars630@gmail.com
    password: testcars630!@#
    port: 587
    protocol: smt.
    properties:
      mail.smtps.auth: true
      mail.starttls.enable: true